name: Build

on:
    push:
        branches:
            - master
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4

            - name: Build and Publish head Docker image
              if: github.ref_name == 'master'
              uses: VaultVulp/gp-docker-action@1.7.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  image-name: "fast-speedtest"
                  image-tag: ${{ github.ref_name }}
                  additional-image-tags: "latest"
                  dockerfile: ci/Dockerfile

            - name: Build and Publish head Docker image
              if: github.ref_name != 'master'
              uses: VaultVulp/gp-docker-action@1.7.0
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  image-name: "fast-speedtest"
                  dockerfile: ci/Dockerfile
                  extract-git-tag: true # Provide flag to extract Docker image tag from git reference
